apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: test
spec:
  selector:
    app: node-app 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080